#!/bin/sh

# Credits to Luke Smith for script https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/compiler

# This script is called by neovim in ~/.config/nvim/init.vim with <leader>c

# This script will take the name of the file open in vim,
# then find the directory, base and extension of the file,
# then it will compile/interpret/open the file with it's specified application

# What files this script can compile/interpret/open:
# - Compiles .md (using pandoc)
# - Can run the python interpreter for .py files in a separate st window
# - Compiles config.h C header files with "make" for suckless apps e.g. dwm, dmenu, st etc.
# - Compiles C++ files using gcc

file=$(readlink -f "$1")
dir=${file%/*}
base="${file%.*}"
ext="${file##*.}"

cd "$dir" || exit 1

case "$ext" in
    md) pandoc -t ms --highlight-style=kate -s -o "$base".pdf "$file" && exit 0 ;;
    py) st -e python "$file" exit 0 ;;
    h) doas make clean install && exit 0 ;;
    cpp) gcc "$base".cpp -lstdc++ -o "$base" && exit 0 ;;
esac

case "$file" in
    /home/dante/.config/touchcursor/touchcursor.conf) systemctl --user restart touchcursor.service ; xset r rate 200 100 ; exit 0 ;;
esac


