#!/bin/sh


# Returns the spotify player instance for playerctl
getSpotify () {  

	if [[ -n $(pgrep brave) ]] ; then  # Brave is running spotify

		# Get the process ID of brave and return the chromium player instance
		local braveid=$(pgrep brave | head -n 1) && local player="chromium.instance$braveid" && echo $player
	elif [[ -n $(pgrep tidal-hifi) ]] ; then  # tidal-hifi is running tidal

		# Get the process ID of tidal-hifi and return the chromium player instance
		local braveid=$(pgrep tidal-hifi | head -n 1) && local player="chromium.instance$braveid" && echo $player
	elif [[ -n $(pgrep spotifyd) ]] ; then  # SpotifyD is running

		# return spotifyd as the current music player
		local braveid=$(pgrep spotifyd | head -n 1) && local player="spotifyd.instance$braveid" && echo $player
	elif [[ -n $(pgrep spotify) ]] ; then  # Spotify is running

		# return spotify as the current music player
		local player="spotify" && echo $player
	fi

}


player=$(getSpotify)

# Uses the argument passed in when calling ./music
# E.g. './music play-pause' or './music next'
[[ $1 == "play-pause" ]] && playerctl --player $player play-pause
[[ $1 == "previous" ]] && playerctl --player $player previous
[[ $1 == "next" ]] && playerctl --player $player next


