#!/bin/sh

# Start qbittorrent-nox depending on whether or not the proper drive has been
# mounted properly and/or plugged in.

# Color codes
Black='\033[0;30m'
Red='\033[0;31m'
Green='\033[0;32m'
Blue='\033[0;34m'
Purple='\033[0;35m'
Cyan='\033[0;36m'
LightGray='\033[0;37m'
DarkGray='\033[1;30m'
LightRed='\033[1;31m'
LightGreen='\033[1;32m'
Yellow='\033[1;33m'
LightBlue='\033[1;34m'
LightPurple='\033[1;35m'
LightCyan='\033[1;36m'
White='\033[1;37m'
NC='\033[0m' # No Color
BOLD=$(tput bold)
NORM=$(tput sgr0)

# CHANGE THESE:
DRIVEUUID='F00D-9045' # Seagate

# automatically mount the slave drive
mountSlaveDrive() {

	# Drive is mounted correctly
	if [[ $(lsblk --fs | awk '/E553-7C9A/ {print $8}') == "/run/media/dante/insignia" ]]; then
			echo -e "${Cyan}=> ${White}Slave drive ${Green}found.${NC}"
			echo -e "${Cyan}=> ${White}Already mounted.${NC}"

	# Not plugged in
	elif [[ -z $(lsblk --fs | grep E553-7C9A ) ]]; then
			echo -e "${Red}#########################################################${NC}"
			echo -e "${Red}#########################################################${NC}"
			echo -e "${Red}#########################################################${NC}"
			echo -e "${Red}#########################################################${NC}"
			echo -e "${Cyan}=> ${White}Slave drive ${Red}not plugged in.${White}${NC}"
			echo -e "${Red}#########################################################${NC}"
			echo -e "${Red}#########################################################${NC}"
			echo -e "${Red}#########################################################${NC}"
			echo -e "${Red}#########################################################${NC}"

	# Plugged in but not mounted anywhere
	elif [[ -z $(lsblk --fs | awk '/E553-7C9A/ {print $8}') ]]; then
			echo -e "${Cyan}=> ${White}Slave drive ${Green}found.${NC}"
			echo -e "${Cyan}=> ${White}Drive ${Orange}not mounted${White}, ${Green}mounting${White}...${NC}"
			udisksctl mount -b /dev/sdc1 && echo -e "${Cyan}=> ${LightGreen}Mounted${White}.${NC}" 
	fi

}


copyqBtStats() {
		echo -e "${Purple}Checking existing directories...${NC}"

		# Create config storage directories if they don't already exist
		[[ -d /run/media/dante/SGHDD/stuff/qBt_backupCONFIG/ ]] || (echo "${LightBlue}Creating qbt backup .config directory...${NC}" && mkdir -v /run/media/dante/SGHDD/stuff/qBt_backupCONFIG/)
		[[ -d /run/media/dante/SGHDD/stuff/qBt_backupLOCALSHARE/ ]] || (echo "${LightBlue}Creating qbt backup .local/share directory...${NC}" && mkdir -v /run/media/dante/SGHDD/stuff/qBt_backupLOCALSHARE/)

		echo -e "${Green}Backup dirs checked.${NC}"

		# Copy files to config storage directories
		echo "Copying qBt config folder to drive for backup..."
		[[ -d $HOME/.config/qBittorrent ]] && cp -rv $HOME/.config/qBittorrent/ /run/media/dante/SGHDD/stuff/qBt_backupCONFIG/. && echo "Backed up!"

		echo "Copying qBt local share config folder to drive for backup..."
		[[ -d $HOME/.local/share/qBittorrent ]] && cp -rv $HOME/.local/share/qBittorrent/ /run/media/dante/SGHDD/stuff/qBt_backupLOCALSHARE/. && echo "Backed up!"
}

getLocalIP() {
    ip a | awk '/192.168/ {print $2}'
}


# echo && if [[ $(mullvad status | awk '{print $3}') == "Connected" ]]; then
echo && if [[ $(mullvad status | awk '{print $1}') == "Connected" ]]; then

		# qBittorrent-nox is not running already
		if [[ -z $(pgrep qbittorrent-nox) ]]; then


				# Drive is mounted correctly
				if [[ $(lsblk --fs | awk '/F00D-9045/ {print $8}') == "/run/media/dante/SGHDD" ]]; then
						echo -e "${Cyan}=> ${White}External drive ${Green}found.${NC}"
						echo -e "${Cyan}=> ${White}Already mounted.${NC}"
						copyqBtStats
						echo -e "${Cyan}=> ${White}Starting ${Yellow}tmux session${White}...${NC}"
						mountSlaveDrive
						tmux new -s qbt -d 'qbittorrent-nox; cp -rv $HOME/.config/qBittorrent/ /run/media/dante/SGHDD/stuff/qBt_backupCONFIG/.; cp -rv $HOME/.local/share/qBittorrent/ /run/media/dante/SGHDD/stuff/qBt_backupLOCALSHARE/.' \;
						echo -e "${Cyan}=> ${Yellow}tmux session ${White}started.${NC}"
						echo -e "${White}$(tmux ls)${NC}"
						echo $(getLocalIP)

				# Not plugged in
				elif [[ -z $(lsblk --fs | grep F00D-9045 ) ]]; then
						echo -e "${Cyan}=> ${White}External drive ${Red}not plugged in.${White} Try again...${NC}"

				# Plugged in but not mounted anywhere
				elif [[ -z $(lsblk --fs | awk '/F00D-9045/ {print $8}') ]]; then
						echo -e "${Cyan}=> ${White}External drive ${Green}found.${NC}"
						echo -e "${Cyan}=> ${White}Drive ${Orange}not mounted${White}, ${Green}mounting${White}...${NC}"
						udisksctl mount -b /dev/sdb1 && echo -e "${Cyan}=> ${LightGreen}Mounted${White}.${NC}" 
						copyqBtStats
						echo -e "${Cyan}=> ${White}Starting ${Yellow}tmux session${White}...${NC}"
						mountSlaveDrive
						tmux new -s qbt -d 'qbittorrent-nox; cp -rv $HOME/.config/qBittorrent/ /run/media/dante/SGHDD/stuff/qBt_backupCONFIG/.; cp -rv $HOME/.local/share/qBittorrent/ /run/media/dante/SGHDD/stuff/qBt_backupLOCALSHARE/.' \;
						echo -e "${Cyan}=> ${Yellow}tmux session ${White}started.${NC}"
						echo -e "${White}$(tmux ls)${NC}"
						echo $(getLocalIP)
				fi
		else  # qbittorrent-nox is already running
			echo -e "${Cyan}=> ${BOLD}${White}qbittorrent-nox is ${Green}already running${White}.${NC}${NORM}"
			echo -e "${Cyan}=> ${White}Exiting...${NC}"
		fi

else
		echo -e "${Cyan}=> ${BOLD}${Red}Warning! ${BOLD}${LightRed}Mullvad VPN is not connected.${NC}${NORM}"
		echo -e "${Cyan}=> ${White}Connect and try again.${NC}"
		echo -e "${Cyan}=> ${White}Aborting...${NC}"
fi

echo ""
