#!/bin/sh

# Start qbittorrent-nox depending on whether or not the proper drive has been
# mounted properly and/or plugged in.

# Color codes
Black='\033[0;30m'
Red='\033[0;31m'
Green='\033[0;32m'
Blue='\033[0;34m'
Purple='\033[0;35m'
Cyan='\033[0;36m'
LightGray='\033[0;37m'
DarkGray='\033[1;30m'
LightRed='\033[1;31m'
LightGreen='\033[1;32m'
Yellow='\033[1;33m'
LightBlue='\033[1;34m'
LightPurple='\033[1;35m'
LightCyan='\033[1;36m'
White='\033[1;37m'
NC='\033[0m' # No Color
BOLD=$(tput bold)
NORM=$(tput sgr0)

copyqBtStats() {
		echo "Copying qBt config folder to drive for backup..."
		[[ -d $HOME/.config/qBittorrent ]] && cp -rv $HOME/.config/qBittorrent/ /run/media/dante/SGHDD/stuff/qBt_backup/ && echo "Backed up!"
}

getLocalIP() {
    ip a | awk '/192.168/ {print $2}'
}


# echo && if [[ $(mullvad status | awk '{print $3}') == "Connected" ]]; then
echo && if [[ $(mullvad status | awk '{print $1}') == "Connected" ]]; then

		# qBittorrent-nox is not running already
		if [[ -z $(pgrep qbittorrent-nox) ]]; then


				# Drive is mounted correctly
				if [[ $(lsblk --fs | awk '/F00D-9045/ {print $8}') == "/run/media/dante/SGHDD" ]]; then
						echo -e "${Cyan}=> ${White}External drive ${Green}found.${NC}"
						echo -e "${Cyan}=> ${White}Already mounted.${NC}"
						copyqBtStats
						echo -e "${Cyan}=> ${White}Starting ${Yellow}tmux session${White}...${NC}"
						tmux new -s qbt -d 'qbittorrent-nox' \;
						echo -e "${Cyan}=> ${Yellow}tmux session ${White}started.${NC}"
						echo -e "${White}$(tmux ls)${NC}"
						echo $(getLocalIP)

				# Not plugged in
				elif [[ -z $(lsblk --fs | grep F00D-9045 ) ]]; then
						echo -e "${Cyan}=> ${White}External drive ${Red}not plugged in.${White} Try again...${NC}"

				# Plugged in but not mounted anywhere
				elif [[ -z $(lsblk --fs | awk '/F00D-9045/ {print $8}') ]]; then
						echo -e "${Cyan}=> ${White}External drive ${Green}found.${NC}"
						echo -e "${Cyan}=> ${White}Drive ${Orange}not mounted${White}, ${Green}mounting${White}...${NC}"
						udisksctl mount -b /dev/sdb1 && echo -e "${Cyan}=> ${LightGreen}Mounted${White}.${NC}" 
						copyqBtStats
						echo -e "${Cyan}=> ${White}Starting ${Yellow}tmux session${White}...${NC}"
						tmux new -s qbt -d 'qbittorrent-nox' \;
						echo -e "${Cyan}=> ${Yellow}tmux session ${White}started.${NC}"
						echo -e "${White}$(tmux ls)${NC}"
						echo $(getLocalIP)
				fi
		else  # qbittorrent-nox is already running
			echo -e "${Cyan}=> ${BOLD}${White}qbittorrent-nox is ${Green}already running${White}.${NC}${NORM}"
			echo -e "${Cyan}=> ${White}Exiting...${NC}"
		fi

else
		echo -e "${Cyan}=> ${BOLD}${Red}Warning! ${BOLD}${LightRed}Mullvad VPN is not connected.${NC}${NORM}"
		echo -e "${Cyan}=> ${White}Connect and try again.${NC}"
		echo -e "${Cyan}=> ${White}Aborting...${NC}"
fi

echo ""
