#!/bin/sh

# transfer qbt config data from hdd to laptop

# remove existing dirs and replace them with existing backed up dirs from hdd
rm -rf $HOME/.config/qBittorrent/ && cp -r /run/media/dante/SGHDD/stuff/qBt_backupCONFIG/qBittorrent/ $HOME/.config/qBittorrent
rm -rf $HOME/.local/share/qBittorrent/ && cp -r /run/media/dante/SGHDD/stuff/qBt_backupLOCALSHARE/qBittorrent/ $HOME/.local/share/qBittorrent/

echo "info transferred, done!"

echo "patching configs for ports..."

[[ $HOSTNAME == "t420" ]] && patch $HOME/.config/qBittorrent/qBittorrent.conf < /run/media/dante/SGHDD/stuff/diffs/t420.diff
[[ $HOSTNAME == "archbox" ]] && patch $HOME/.config/qBittorrent/qBittorrent.conf < /run/media/dante/SGHDD/stuff/diffs/archbox.diff
