#!/bin/sh

# Start recording the screen with ffmpeg with these settings.

ffmpeg -f x11grab -video_size 1920x1080 -framerate 25 -i $DISPLAY -f alsa -i default -c:v libx264 -preset ultrafast -c:a aac ~/personal/videos/recordings/screen.mp4
