#!/bin/sh

# Written by Dante Fernando

# Opens programs defined here when script is called

programs=('st' 'firefox' 'barrier')

# Put scripts here with different names to the respective programs that they open 
declare -A scripts

# Assign more scripts to the dict here:
# Ex: scripts[script]="applicationItOpens"
# 'application' is what is used to search
# to see if the program is already running.
#       script| application
scripts[spotifyb]="brave"
scripts[discord]="Discord"

#############################################

# Iterates through array of programs to open,
# If the program isn't running, start it
for program in "${programs[@]}"; do
	[[ -z $(pgrep $program) ]] && ($program &)
done

# Iterates through scripts dictionary
# Gets key (script) and application (value)
# If the program isn't running, start it
for script in "${!scripts[@]}"; do
	application=${scripts[$script]}
	[[ -z $(pgrep $application) ]] && ($script &)
done

