#!/bin/sh

# Returns the spotify song title and artist from playerctl
getTrack () {

	title=$(playerctl --player $player metadata title)
	artist=$(playerctl --player $player metadata artist)
	status=$(playerctl --player $player status)

	if [ $? == 0 ] ; then

		case $status in
				"Playing") icon="🎵" ;;
				"Paused") icon="" ;;
		esac

	# [[ $title != "Advertisement" ]] && echo "$icon  $artist - $title "
		# [[ -z $(playerctl --player $player metadata | grep spotify:ad) ]] && echo "$icon  $artist - $title "
		[[ -z $(playerctl --player $player metadata | grep spotify:ad) ]] && echo "$icon  $title - $artist"
	fi

}

# If spotify is running, call getTrack function
getSpotify () {

	if [[ -n $(pgrep brave) ]] ; then  # Brave is running spotify
		# player=$(playerctl -l | grep chromium)
		braveid=$(pgrep brave | head -n 1)
		player="chromium.instance$braveid"
		echo $(getTrack)
	elif [[ -n $(pgrep spotify) ]] ; then  # Spotify is running
		player="spotify"
		echo $(getTrack)
	fi

}

getSpotify

